In [30]:
# ML STEPS:
# problem analysis
# data collection
# data prep(visualization)
# label the data
# splitting the data for train and test
# model selection
# model training
# model testing
# model evaluation
# model deployment
import pandas as pd
df=pd.read_csv("ipl.csv")

In [31]:
columns_to_remove=['mid','venue','batsman','bowler','striker','non-striker']
print("Before removing unwanted columns:",df.shape)

df.drop(labels=columns_to_remove,axis=1,inplace=True)
print("After removing unwanted columns:",df.shape)

Before removing unwanted columns: (76014, 15)
After removing unwanted columns: (76014, 9)

In [32]:
consistent_teams=['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians','Kings XI Punjab', 'Royal Challengers Bangalore', 'Delhi Daredevils','Sunrisers Hyderabad']
print("Before Removing inconsistent teams:",df.shape)
df=df[(df['bat_team'].isin(consistent_teams))&(df['bowl_team'].isin(consistent_teams))]
print("After removing inconsistent teams:",df.shape)

Before Removing inconsistent teams: (76014, 9)
After removing inconsistent teams: (53811, 9)

In [33]:
print("After removing first 5 overs")
df=df[df['overs']>=5.0]
df.shape

After removing first 5 overs

(40108, 9)

In [34]:
df

,date,bat_team,bowl_team,runs,wickets,overs,runs_last_5,wickets_last_5,total
32,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,0,5.1,59,0,222
33,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.2,59,1,222
34,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.3,59,1,222
35,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.4,59,1,222
36,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,61,1,5.5,58,1,222
...,...,...,...,...,...,...,...,...,...
75884,2017-05-19,Kolkata Knight Riders,Mumbai Indians,106,9,18.1,29,4,107
75885,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,9,18.2,29,4,107
75886,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,9,18.3,28,4,107
75887,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,9,18.4,24,4,107
75888,2017-05-19,Kolkata Knight Riders,Mumbai Indians,107,10,18.5,23,5,107

In [35]:
# converting date object to datetime object
from datetime import datetime
print("Before converting 'date' column from string to datetime:",type(df.iloc[0,0]))

df['date']=df['date'].apply(lambda x: datetime.strptime(x,'%Y-%m-%d'))
print("After converting 'date' column from string to datetime:",type(df.iloc[0,0]))

Before converting 'date' column from string to datetime: <class 'str'>
After converting 'date' column from string to datetime: <class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [7]:
df.dtypes

date              datetime64[ns]
bat_team                  object
bowl_team                 object
runs                       int64
wickets                    int64
overs                    float64
runs_last_5                int64
wickets_last_5             int64
total                      int64
dtype: object

In [8]:
df=pd.get_dummies(df,columns=['bat_team','bowl_team'],dtype='int')
df

,date,runs,wickets,overs,runs_last_5,wickets_last_5,total,bat_team_Chennai Super Kings,bat_team_Delhi Daredevils,bat_team_Kings XI Punjab,...,bat_team_Royal Challengers Bangalore,bat_team_Sunrisers Hyderabad,bowl_team_Chennai Super Kings,bowl_team_Delhi Daredevils,bowl_team_Kings XI Punjab,bowl_team_Kolkata Knight Riders,bowl_team_Mumbai Indians,bowl_team_Rajasthan Royals,bowl_team_Royal Challengers Bangalore,bowl_team_Sunrisers Hyderabad
32,2008-04-18,61,0,5.1,59,0,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
33,2008-04-18,61,1,5.2,59,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34,2008-04-18,61,1,5.3,59,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
35,2008-04-18,61,1,5.4,59,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
36,2008-04-18,61,1,5.5,58,1,222,0,0,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75884,2017-05-19,106,9,18.1,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75885,2017-05-19,107,9,18.2,29,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75886,2017-05-19,107,9,18.3,28,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75887,2017-05-19,107,9,18.4,24,4,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0
75888,2017-05-19,107,10,18.5,23,5,107,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [9]:
df=df[['date','bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad','bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad','runs', 'wickets', 'overs', 'runs_last_5', 'wickets_last_5',
       'total']]

In [10]:
# labelling the data
x=df.drop('total',axis=1)
# splitting the data for training and testing
x_train=x[x['date'].dt.year<=2016]
x_test=x[x['date'].dt.year>=2017]
x_train.drop('date',axis=1,inplace=True)
x_test.drop('date',axis=1,inplace=True)
# output training and testing
y_train=df[df['date'].dt.year<=2016]['total'].values
y_test=df[df['date'].dt.year>=2017]['total'].values

C:\Users\devas\AppData\Local\Temp\ipykernel_8172\1785855386.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train.drop('date',axis=1,inplace=True)
C:\Users\devas\AppData\Local\Temp\ipykernel_8172\1785855386.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test.drop('date',axis=1,inplace=True)

In [11]:
print(x_train.shape)
print(x_test.shape)

(37330, 21)
(2778, 21)

In [12]:
print(y_train.shape)
print(y_test.shape)

(37330,)
(2778,)

In [13]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\devas\appdata\local\programs\python\python314\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\devas\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (2.4.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\devas\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\devas\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\devas\appdata\local\programs\python\python314\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
from sklearn.linear_model import LinearRegression

# create object for the class
lr=LinearRegression()

# training the model
lr.fit(x_train,y_train)

LinearRegression()

In [15]:
# model testing
lr_pred=lr.predict(x_test)
lr_pred

array([172.07093429, 175.2197967 , 174.61607874, ..., 100.37504751,
        99.80473879,  93.14382211], shape=(2778,))

In [16]:
# model evaluation
print("Score of LR on training set:",lr.score(x_train,y_train))
print("Score of LR on training set:",lr.score(x_test,y_test))

Score of LR on training set: 0.6502133812161469
Score of LR on training set: 0.7522633566350524

In [17]:
# error metrics
import numpy as np
from sklearn.metrics import mean_absolute_error as mae,mean_squared_error as mse
print("----Linear Regression----")
print("Mean Absolute Error(MAE):",mae(y_test,lr_pred))
print("Mean Squared Error(MSE):",mse(y_test,lr_pred))
print("Root Mean Squared Error:",np.sqrt(mse(y_test,lr_pred)))

----Linear Regression----
Mean Absolute Error(MAE): 12.11861754619329
Mean Squared Error(MSE): 251.00792310417467
Root Mean Squared Error: 15.843229566732115

In [18]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

In [19]:
dtr=DecisionTreeRegressor()
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [20]:
dtr_pred=dtr.predict(x_test)
dtr_pred

array([194., 194., 194., ..., 119., 112., 112.], shape=(2778,))

In [21]:
print("Score of DTR on training set:",dtr.score(x_train,y_train))
print("Score of DTR on training set:",dtr.score(x_test,y_test))

Score of DTR on training set: 0.9998567447518953
Score of DTR on training set: 0.475056967618099

In [22]:
print("Mean Absolute Error(MAE):",mae(y_test,dtr_pred))
print("Mean Squared Error(MSE):",mse(y_test,dtr_pred))
print("Root Mean Squared Error:",np.sqrt(mse(y_test,dtr_pred)))

Mean Absolute Error(MAE): 17.067674586033117
Mean Squared Error(MSE): 531.8747300215982
Root Mean Squared Error: 23.062409458285103

In [23]:
rfr=RandomForestRegressor()
rfr.fit(x_train,y_train)

RandomForestRegressor()

In [24]:
rfr_pred=rfr.predict(x_test)
rfr_pred

array([186.25, 188.54, 188.25, ..., 117.69, 115.27, 114.87], shape=(2778,))

In [25]:
print("Score of RFR on training set:",rfr.score(x_train,y_train))
print("Score of RFR on training set:",rfr.score(x_test,y_test))

Score of RFR on training set: 0.9924133854999342
Score of RFR on training set: 0.6650434894098602

In [26]:
print("Mean Absolute Error(MAE):",mae(y_test,rfr_pred))
print("Mean Squared Error(MSE):",mse(y_test,rfr_pred))
print("Root Mean Squared Error:",np.sqrt(mse(y_test,rfr_pred)))

Mean Absolute Error(MAE): 13.857812574994
Mean Squared Error(MSE): 339.37949958253336
Root Mean Squared Error: 18.422255550896402

In [48]:
svr=SVR()
svr.fit(x_train,y_train)

SVR()

In [49]:
svr_pred=svr.predict(x_test)
svr_pred

array([168.76358772, 174.61807174, 172.40291379, ..., 121.23345   ,
       118.4923028 , 114.33738668], shape=(2778,))

In [ ]:
print("Score of SVR on training set:",svr.score(x_train,y_train))
print("Score of SVR on training set:",svr.score(x_test,y_test))

In [ ]:
print("Mean Absolute Error(MAE):",mae(y_test,svr_pred))
print("Mean Squared Error(MSE):",mse(y_test,svr_pred))
print("Root Mean Squared Error:",np.sqrt(mse(y_test,svr_pred)))

In [27]:
x_train.columns

Index(['bat_team_Chennai Super Kings', 'bat_team_Delhi Daredevils',
       'bat_team_Kings XI Punjab', 'bat_team_Kolkata Knight Riders',
       'bat_team_Mumbai Indians', 'bat_team_Rajasthan Royals',
       'bat_team_Royal Challengers Bangalore', 'bat_team_Sunrisers Hyderabad',
       'bowl_team_Chennai Super Kings', 'bowl_team_Delhi Daredevils',
       'bowl_team_Kings XI Punjab', 'bowl_team_Kolkata Knight Riders',
       'bowl_team_Mumbai Indians', 'bowl_team_Rajasthan Royals',
       'bowl_team_Royal Challengers Bangalore',
       'bowl_team_Sunrisers Hyderabad', 'runs', 'wickets', 'overs',
       'runs_last_5', 'wickets_last_5'],
      dtype='object')

In [38]:
# creating a function for prediction
def predict_score(bat_team='Mumbai Indians',bowl_team='Delhi Daredevils',runs=120,wickets=4,overs=6.2,runs_last_5=33,wickets_last_5=1):
    temp_array=list()
    if bat_team == 'Chennai Super Kings':
        temp_array=temp_array+[1,0,0,0,0,0,0,0]
    elif bat_team == 'Delhi Daredevils':
        temp_array=temp_array+[0,1,0,0,0,0,0,0]
    elif bat_team == 'Kings XI Punjab':
        temp_array=temp_array+[0,0,1,0,0,0,0,0]
    elif bat_team == 'Kolkata Knight Riders':
        temp_array=temp_array+[0,0,0,1,0,0,0,0]
    elif bat_team == 'Mumbai Indians':
        temp_array=temp_array+[0,0,0,0,1,0,0,0]
    elif bat_team == 'Rajasthan Royals':
        temp_array=temp_array+[0,0,0,0,0,1,0,0]
    elif bat_team == 'Royal Challengers Bangalore':
        temp_array=temp_array+[0,0,0,0,0,0,1,0]
    elif bat_team == 'Sunrisers Hyderabad':
        temp_array=temp_array+[0,0,0,0,0,0,0,1]
        
    if bowl_team == 'Chennai Super Kings':
        temp_array=temp_array+[1,0,0,0,0,0,0,0]
    elif bowl_team == 'Delhi Daredevils':
        temp_array=temp_array+[0,1,0,0,0,0,0,0]
    elif bowl_team == 'Kings XI Punjab':
        temp_array=temp_array+[0,0,1,0,0,0,0,0]
    elif bowl_team == 'Kolkata Knight Riders':
        temp_array=temp_array+[0,0,0,1,0,0,0,0]
    elif bowl_team == 'Mumbai Indians':
        temp_array=temp_array+[0,0,0,0,1,0,0,0]
    elif bowl_team == 'Rajasthan Royals':
        temp_array=temp_array+[0,0,0,0,0,1,0,0]
    elif bowl_team == 'Royal Challengers Bangalore':
        temp_array=temp_array+[0,0,0,0,0,0,1,0]
    elif bowl_team == 'Sunrisers Hyderabad':
        temp_array=temp_array+[0,0,0,0,0,0,0,1]
    
    temp_array=temp_array+[runs,wickets,overs,runs_last_5,wickets_last_5]

    # converting to numpy array
    temp_array=np.array([temp_array])

    # prediction
    return int(lr.predict(temp_array)[0])

In [39]:
# final prediction
final_score= predict_score(bat_team='Kolkata Knight Riders',bowl_team='Mumbai Indians',runs=120,wickets=9,overs=18.2,runs_last_5=29,wickets_last_5=4)
print("Final Predicted Score is {} to {}".format(final_score-5,final_score+10))

Final Predicted Score is 108 to 123

C:\Users\devas\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [45]:
!pip install --upgrade pip
!pip install pickle

Requirement already satisfied: pip in c:\users\devas\appdata\local\programs\python\python314\lib\site-packages (25.3)
Collecting pip
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: To modify pip, please run the following command:
C:\Users\devas\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip
ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pickle

In [46]:
#saving the model(pkl file)
import pickle

In [47]:
with open("ipl.pkl","wb")as f:
    pickle.dump(lr,f)